# Generated by Django 5.2.1 on 2025-06-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_profile_avatar_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
