# Generated by Django 5.2.1 on 2025-06-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_remove_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
