# Generated by Django 5.2.1 on 2025-05-31 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_category_todo_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='category',
            new_name='categories',
        ),
    ]
