# Generated by Django 5.2.1 on 2025-06-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_auto_20250601_2036'),
    ]

    operations = [
    ]
