# Generated by Django 5.2.1 on 2025-06-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0014_profile_first_name_profile_last_name_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
