# Generated by Django 5.2.1 on 2025-06-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0021_alter_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='first_name',
            field=models.CharField(default='First', max_length=30),
        ),
    ]
