# Generated by Django 5.2.1 on 2025-06-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0022_todo_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='first_name',
        ),
    ]
